Run VERSION=1.0.6
wix.exe : error WIX0118: Additional argument '--accept-eula' was unexpected. Remove the argument and add the '-?' switch for more information.
wix.exe : error WIX7015: You must accept the Open Source Maintenance Fee (OSMF) EULA to use WiX Toolset v7. For instructions, see https://wixtoolset.org/osmf/
Error: Process completed with exit code 1.
